title: מסדר הסינגלים - סדר במוזיקה שלך, בקליק אחד
description: >-
  האתר הרשמי של מסדר הסינגלים. התוכנה היחידה שמזהה, ממיינת ומסדרת אוטומטית את אוסף המוזיקה היהודית והישראלית שלך, וחוסכת לך שעות של עבודה ידנית.
baseurl: ""
url: "https://singles-sorter.ze-kal.top"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - legacy/